foreground=#ffffff
background=#222222
cursor=#eeeeee

color0=#444444
color1=#ff8888
color2=#88ff88
color3=#ffff88
color4=#8888ff
color5=#ff88ff
color6=#88ffff
color7=#dddddd

color8=#aaaaaa
color9=#ffaaaa
color10=#aaffaa
color11=#ffffaa
color12=#aaaaff
color13=#ffaaff
color14=#aaffff
color15=#ffffff
