#special
foreground=#f4f4f4
cursor=#d4d4d4
background=#161616

# black
color0=#000000
color8=#444444

# red
color1=#ff6666
color9=#ffaaaa

# green
color2=#66ff66
color10=#aaffaa

# yellow
color3=#ffff66
color11=#ffffaa

# blue
color4=#6666ff
color12=#aaaaff

# magenta
color5=#ff79c6
color13=#ff92d0

# cyan
color6=#8be9fd
color14=#9aedfe

# white
color7=#aaaaaa
color15=#eeeeee
