#!/data/data/com.termux/files/usr/bin/bash

## Commands to copy & paste

# Download Script from my GitHub

bash -c 'read -p "Enter Script Name : " script && apt update && yes | pkg install curl && curl https://raw.githubusercontent.com/abdullah-al-jaber/abdullah-al-jaber/vanilla/termux/scripts/$script && chmod +x ./$script'

## Use it as you wish
